### ISSUE TITLE
Plugin is throwing TypeError: Cannot read properties of undefined (reading 'pushEvent') error

### ISSUE THREAD

**Issue by jalalomary** [boazreicher/mosaic-plot#9]
Hi,

I am trying to use the plugin on Grafana and it's throwing the following error when ever I try it. Grafana version: 10.4.1

Error:

```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'pushEvent')

    at r (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:194:122076)
    at div
    at div
    at x (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:214:30856)
    at yn (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:2551:35440)
    at dn (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:2551:44435)
    at lt (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:433:32639)
    at div
    at div
    at div
    at b (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:475:101103)
    at div
    at div
    at div
    at o (http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:2299)
    at div
    at o (http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:4287)
    at N (http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:9622)
    at div
    at o (http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:2299)
    at div
    at o (http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:4287)
    at N (http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:9622)
    at div
    at div
    at div
    at U (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:370:21108)
    at Bn (http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:130:526)
    at lt (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:433:32639)
    at WithTheme(Connect(Bn))
    at yt (http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:205:472)
    at DashboardPage
    at lt (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:433:32639)
    at ms (http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:205:6334)
    at Suspense
    at r (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:194:122076)
    at vi (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:315:9679)
    at U (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:465:29190)
    at gi (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:456:4455)
    at si (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:456:12005)
    at mt (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:465:17389)
    at U (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:465:31358)
    at div
    at div
    at main
    at div
    at wa (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:315:2409)
    at gi (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:456:4455)
    at si (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:456:12005)
    at hr (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:456:11341)
    at Yn (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:465:17688)
    at U (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:465:25428)
    at div
    at o (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:214:13884)
    at d (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:136:9042)
    at h (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:794:96447)
    at d (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:599:21166)
    at r (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:194:122076)
    at g (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:194:122585)
    at ot (http://localhost:3000/public/build/8838.275a4549ebab360e94cc.js:437:529)
    at fr (http://localhost:3000/public/build/6279.d4f9723e8eecd7fa8edb.js:326:127)
```

**Comment by boazreicher** [comment]
Hi @jalalomary , would you be able to provide some more information?  What's the datasource when this happens?  Does it happen when using certain configuration options?
